http://localhost:8085

###

http://localhost:8085/tree/100005870

###

http://localhost:8085/trees

###

POST http://localhost:8085/create
Content-Type: application/json; charset=utf-8
Accept: application/json

{
    "id": 1000,
    "baum_nr": "M401-9-1000",
    "sorte_nr": 38,
    "pflanzjahr": 1990,
    "krone": 5,
    "stamm": 50,
    "strasse": "HCU Hamburg",
    "haus_nr": "8", 
    "ortsteil_nr": 107, 
    "longitude": 10.005,
    "latitude": 53.04
}

###

PUT http://localhost:8085/update
Content-Type: application/json; charset=utf-8
Accept: application/json

{
    "id": 1000,
    "baum_nr": "M401-9-1000",
    "sorte_nr": 38,
    "pflanzjahr": 1990,
    "krone": 5,
    "stamm": 50,
    "strasse": "HCU Hamburg",
    "haus_nr": "8", 
    "ortsteil_nr": 107, 
    "longitude": 10.005,
    "latitude": 53.04
}
###

DELETE http://localhost:8085/remove
Content-Type: application/json; charset=utf-8
Accept: application/json

{
    "id": 1000
}